#----------------DRIVER PATH----------------
CHROME_DRIVER_PATH_WINS:       /Drivers/chromedriver.exe
CHROME_DRIVER_PATH_UNIX:       /usr/local/bin/chromedriver

#Browsers: Chrome/FireFox/IE
#BROWSER:  Chrome

#----------------SET DEFAULT ENVIRONMENT----------------
ENV: QA

#----------------SYSTEM ENVIRONMENT----------------
ENVIRONMENT:
  QA:
    BASE_URL: https://github.com/
    HOME_PAGE_URL: 
    LOGOUT_URL: 

  DEV:
    BASE_URL: https://github.com/
    HOME_PAGE_URL:
    LOGOUT_URL: 

#----------------ACCOUNT LOGIN---------------
ACCOUNTS:
  UAT:
    USERNAME_0:     
    PASSWORD:       

  DEV:
    USERNAME_1:     
    PASSWORD:       
